// [word, IPA (British), part of speech, 中文意思, 廣東話解釋, example, example 中譯, 用法貼士]
const WORDS_RAW = [
// ---- 第 1 週：日常生活 ----
["busy","/ˈbɪzi/","adj.","忙碌","形容有好多嘢做、冇乜時間。","I'm very busy today.","我今日好忙。","busy with + 名詞：I'm busy with work.（我忙緊做嘢）"],
["tired","/ˈtaɪəd/","adj.","疲倦；攰","身體或者精神好攰，想唞下。","I feel tired after work.","放工之後我覺得好攰。","be tired of = 厭倦：I'm tired of waiting.（我等到厭晒）"],
["hungry","/ˈhʌŋgri/","adj.","肚餓","肚餓、想食嘢。","Are you hungry now?","你而家肚唔肚餓？","肚餓用 hungry；口渴就用 thirsty。"],
["breakfast","/ˈbrekfəst/","n.","早餐","一日第一餐，即係早餐。","I have breakfast at seven.","我七點食早餐。","「食早餐」講 have breakfast，前面唔使加 the。"],
["traffic","/ˈtræfɪk/","n.","交通；車流","路面上嘅車同人流。","The traffic is bad today.","今日交通好差（好塞車）。","塞車 = traffic jam：I was stuck in a traffic jam.（我塞咗車）"],
["late","/leɪt/","adj.","遲；遲到","遲咗、晏咗，冇準時。","Sorry, I am late again.","唔好意思，我又遲到。","be late for + 事情：I was late for work.（我返工遲到）"],
["weather","/ˈweðə/","n.","天氣","天氣，例如晴天、落雨、打風。","The weather is nice today.","今日天氣好好。","唔好同 whether（是否）搞亂，兩個字讀音差唔多。"],
["umbrella","/ʌmˈbrelə/","n.","雨傘；遮","落雨用嘅遮。","Take an umbrella with you.","帶把遮喺身啦。","umbrella 係元音開頭，所以講 an umbrella。"],
["forget","/fəˈget/","v.","忘記；唔記得","唔記得某樣嘢或者某件事。","Don't forget your keys.","唔好唔記得帶鎖匙。","過去式係 forgot；forget to do = 唔記得去做某事。"],
["cheap","/tʃiːp/","adj.","便宜；平","價錢平、唔貴。","This shirt is very cheap.","呢件恤衫好平。","想講得客氣啲可以用 affordable（價錢相宜）。"],
["expensive","/ɪkˈspensɪv/","adj.","昂貴；貴","價錢高、好貴。","Hong Kong rent is expensive.","香港租金好貴。","比較級係 more expensive，唔係 expensiver。"],
["price","/praɪs/","n.","價錢","買嘢要俾幾多錢。","What is the price of this bag?","呢個袋幾多錢？","價錢用 high / low 形容：The price is high.（唔講 expensive price）"],
["order","/ˈɔːdə/","v.","點（菜）；訂購","喺餐廳叫嘢食，或者網上訂嘢。","Can I order a milk tea?","我可唔可以叫杯奶茶？","order food / order online（網購）；名詞：Can I take your order?（請問想點啲咩？）"],
["menu","/ˈmenjuː/","n.","菜單；餐牌","餐廳嘅餐牌；電腦嘅選單都叫 menu。","Can I see the menu, please?","可唔可以畀個餐牌我睇下？","on the menu = 餐牌上有：Is fish on the menu?"],
["bill","/bɪl/","n.","帳單","餐廳埋單張單，或者水電費單。","Can we have the bill, please?","唔該埋單。","美式英文埋單多數講 check；pay the bill = 俾錢。"],
["healthy","/ˈhelθi/","adj.","健康的","健康、對身體好。","She eats healthy food every day.","佢每日都食健康嘢。","反義詞係 unhealthy；stay healthy = 保持健康。"],
["exercise","/ˈeksəsaɪz/","v.","做運動","做運動；做名詞時亦可以解「練習題」。","I exercise three times a week.","我一個星期做三次運動。","名詞用法：do exercise / get some exercise（做運動）。"],
["sleep","/sliːp/","v.","睡覺；瞓覺","瞓覺、休息。","I need to sleep early tonight.","我今晚要早啲瞓。","過去式 slept；go to sleep = 入瞓；fall asleep = 瞓着咗。"],
["weekend","/ˌwiːkˈend/","n.","週末","週末，即係星期六同星期日。","What did you do at the weekend?","你週末做咗啲咩？","英式講 at the weekend，美式講 on the weekend。"],
["relax","/rɪˈlæks/","v.","放鬆","放鬆、唞下，唔好咁緊張。","I like to relax at home.","我鍾意喺屋企放鬆下。","relaxed 形容人覺得輕鬆；relaxing 形容嘢令人輕鬆。"],
["plan","/plæn/","n.","計劃","計劃、打算；亦可以做動詞。","What is your plan for tomorrow?","你聽日有咩計劃？","plan to do：I plan to travel.（我打算去旅行）"],
// ---- 第 2 週：返工 ----
["meeting","/ˈmiːtɪŋ/","n.","會議","開會、會議。","We have a meeting at ten.","我哋十點要開會。","開會 = have / hold a meeting；attend a meeting = 出席會議。"],
["email","/ˈiːmeɪl/","n.","電郵","電子郵件；亦可以做動詞：email someone。","Please send me an email.","請你寄封電郵畀我。","email 係元音開頭，所以講 an email。"],
["reply","/rɪˈplaɪ/","v.","回覆","覆人、回覆訊息。","Please reply to my email soon.","請盡快回覆我封電郵。","reply to + 人／訊息，唔好漏咗 to：reply to him。"],
["colleague","/ˈkɒliːg/","n.","同事","一齊返工嘅人，即係同事。","My colleague helps me a lot.","我同事幫咗我好多。","讀音似「call-leeg」，尾嗰個 -ue 唔發音。"],
["manager","/ˈmænɪdʒə/","n.","經理","經理、主管、上司。","I need to ask my manager.","我要問下我經理先。","重音喺第一個音節：MAN-a-ger。"],
["office","/ˈɒfɪs/","n.","辦公室","辦公室、公司返工嘅地方。","I get to the office at nine.","我九點返到公司。","返工可以講 go to the office 或者 go to work。"],
["deadline","/ˈdedlaɪn/","n.","截止日期","最遲要完成嘅時間，即係「死線」。","The deadline is next Friday.","限期係下個禮拜五。","meet the deadline = 趕得切；miss the deadline = 趕唔切。"],
["finish","/ˈfɪnɪʃ/","v.","完成","做完、完成。","I will finish the work today.","我今日會做完啲嘢。","finish + 動詞-ing：I finished reading the book.（我睇完本書）"],
["report","/rɪˈpɔːt/","n.","報告","報告；亦可以做動詞：匯報。","Please read this report first.","請你先睇咗呢份報告。","write a report = 寫報告；report to someone = 向某人匯報。"],
["appointment","/əˈpɔɪntmənt/","n.","預約","約好嘅時間，例如睇醫生、見客。","I have an appointment at three.","我三點有個預約。","make an appointment = 約時間；同朋友出街通常唔用呢個字。"],
["available","/əˈveɪləbl/","adj.","有空；可用的","得閒；或者有得用、有貨。","Are you available on Monday?","你星期一得唔得閒？","Are you available? 比 Are you free? 更正式，適合返工用。"],
["cancel","/ˈkænsl/","v.","取消","取消原本安排好嘅嘢。","We have to cancel the trip.","我哋要取消個旅程。","英式過去式寫 cancelled（兩個 l），美式寫 canceled。"],
["salary","/ˈsæləri/","n.","薪金；人工","每個月出嘅糧、人工。","He gets his salary every month.","佢每個月出糧。","加人工 = get a pay rise；出糧 = get paid。"],
["holiday","/ˈhɒlədeɪ/","n.","假期","放假；英式英文亦解作去旅行度假。","We are going on holiday next week.","我哋下個禮拜去度假。","go on holiday = 去度假；public holiday = 公眾假期。"],
["overtime","/ˈəʊvətaɪm/","adv.","超時工作","放工時間之後繼續做，即係「OT」。","I worked overtime last night.","我琴晚開 OT。","work overtime = 開 OT；overtime pay = OT 錢。"],
["problem","/ˈprɒbləm/","n.","問題","問題、麻煩。","There is a problem with my phone.","我部手機有啲問題。","No problem! = 冇問題／唔使客氣。"],
["solve","/sɒlv/","v.","解決","解決問題、解答難題。","Can you help me solve this?","你可唔可以幫我解決呢樣嘢？","solve a problem = 解決問題；solve a puzzle = 解謎。"],
["idea","/aɪˈdɪə/","n.","主意；想法","主意、諗法。","That is a great idea!","呢個主意好正！","I have no idea. = 我完全唔知（冇頭緒）。"],
["customer","/ˈkʌstəmə/","n.","顧客；客人","去舖頭買嘢、用服務嘅人。","The customer wants a refund.","個客想退錢。","customer service = 客戶服務；client 多數指專業服務嘅客戶。"],
["service","/ˈsɜːvɪs/","n.","服務","服務，例如餐廳、銀行提供嘅服務。","The service here is very good.","呢度服務好好。","service charge = 服務費（即係「加一」）。"],
["complain","/kəmˈpleɪn/","v.","投訴；抱怨","對唔滿意嘅嘢表示不滿。","Many people complain about the noise.","好多人投訴啲噪音。","complain about + 事；名詞係 complaint。"],
// ---- 第 3 週：出街・健康・做人 ----
["airport","/ˈeəpɔːt/","n.","機場","搭飛機嘅地方。","We arrived at the airport early.","我哋早咗到機場。","到機場講 arrive at the airport，唔講 arrive to。"],
["passport","/ˈpɑːspɔːt/","n.","護照","出國旅行用嘅身份證明文件。","Please show me your passport.","請出示你嘅護照。","apply for a passport = 申請護照。"],
["luggage","/ˈlʌgɪdʒ/","n.","行李","旅行帶嘅喼同袋。","My luggage is too heavy.","我啲行李太重。","luggage 係不可數名詞：唔講 luggages，要講 a piece of luggage。"],
["direction","/dəˈrekʃn/","n.","方向","方向；複數 directions 解作指路。","Which direction is the station?","車站喺邊個方向？","ask for directions = 問路。"],
["nearby","/ˌnɪəˈbaɪ/","adv.","附近","喺附近、唔遠。","Is there a bank nearby?","附近有冇銀行？","nearby 可以放喺名詞前面（a nearby shop）或者句尾。"],
["crowded","/ˈkraʊdɪd/","adj.","擠迫的","好多人、好迫。","The MTR is very crowded.","港鐵好迫。","be crowded with people = 迫滿人。"],
["fever","/ˈfiːvə/","n.","發燒","體溫高過正常，即係發燒。","My son has a fever.","我個仔發燒。","發燒講 have a fever；英式亦會講 have a temperature。"],
["medicine","/ˈmedsn/","n.","藥","睇醫生攞嘅藥。","Take this medicine after meals.","飯後食呢隻藥。","食藥講 take medicine，唔講 eat medicine。"],
["recover","/rɪˈkʌvə/","v.","康復","病好返、復原。","I hope you recover soon.","希望你早日康復。","recover from + 病：recover from a cold（感冒好返）。"],
["borrow","/ˈbɒrəʊ/","v.","借（入）","由人哋度借嘢嚟用。","Can I borrow your pen?","我可唔可以借你支筆？","borrow = 借入；lend = 借出。borrow something from someone。"],
["lend","/lend/","v.","借（出）","將自己啲嘢借畀人用。","Can you lend me some money?","你可唔可以借啲錢畀我？","lend someone something；過去式係 lent。"],
["return","/rɪˈtɜːn/","v.","歸還；返回","還返畀人；或者返嚟、返去。","Please return the book on Monday.","請你星期一還返本書。","return 已經有「返」嘅意思，唔好講 return back。"],
["decide","/dɪˈsaɪd/","v.","決定","諗清楚之後揀定。","I can't decide what to eat.","我決定唔到食咩好。","decide to do：I decided to quit.；名詞係 decision。"],
["choose","/tʃuːz/","v.","選擇；揀","喺幾樣嘢入面揀一樣。","You can choose any colour.","你可以揀任何顏色。","過去式 chose，過去分詞 chosen。"],
["prefer","/prɪˈfɜː/","v.","比較喜歡","兩樣嘢之中比較鍾意其中一樣。","I prefer tea to coffee.","比起咖啡，我鍾意茶多啲。","prefer A to B（唔係 than）：I prefer tea to coffee."],
["improve","/ɪmˈpruːv/","v.","改善；進步","令某樣嘢變得更好。","I want to improve my English.","我想改善我嘅英文。","名詞係 improvement（改善、進步）。"],
["practice","/ˈpræktɪs/","n.","練習","不斷做嚟令自己更熟練。","Practice makes perfect.","熟能生巧。","英式：practice 係名詞，practise 係動詞；美式兩樣都寫 practice。"],
["mistake","/mɪˈsteɪk/","n.","錯誤","錯處、做錯嘅嘢。","I made a mistake in the email.","我封電郵有個錯。","犯錯講 make a mistake，唔講 do a mistake。"],
["friendly","/ˈfrendli/","adj.","友善的","對人好、易相處。","Our neighbours are very friendly.","我哋啲鄰居好友善。","friendly 雖然係 -ly 結尾，但係形容詞，唔係副詞。"],
["polite","/pəˈlaɪt/","adj.","有禮貌的","講嘢做事有禮貌。","Please be polite to customers.","請對客人有禮貌。","反義詞：impolite / rude（冇禮貌）。"],
["honest","/ˈɒnɪst/","adj.","誠實的","講真話、唔呃人。","Thank you for being honest.","多謝你咁坦白。","h 唔發音，所以講 an honest person。"],
// ---- 第 4 週：職場進階 ----
["experience","/ɪkˈspɪəriəns/","n.","經驗；經歷","做過某啲嘢而累積嘅知識，或者一次經歷。","She has five years of experience.","佢有五年經驗。","解「經驗」時不可數；解「一次經歷」時可數：a great experience。"],
["skill","/skɪl/","n.","技能","識做某樣嘢嘅能力、技巧。","Cooking is a useful skill.","煮飯係一樣有用嘅技能。","communication skills = 溝通技巧（多數用複數）。"],
["confident","/ˈkɒnfɪdənt/","adj.","有信心的","相信自己做得到。","I feel confident about the test.","我對個測驗好有信心。","be confident about / in something；名詞係 confidence。"],
["opportunity","/ˌɒpəˈtjuːnəti/","n.","機會","做某件事嘅好時機。","This is a good opportunity for you.","呢個對你嚟講係個好機會。","take the opportunity = 把握機會。"],
["career","/kəˈrɪə/","n.","事業；職業生涯","長期從事嘅工作同發展。","He wants a career in design.","佢想喺設計界發展事業。","重音喺尾：ca-REER，唔好讀成 carrier。"],
["interview","/ˈɪntəvjuː/","n.","面試；訪問","見工面試，或者記者訪問。","I have a job interview tomorrow.","我聽日要去見工。","job interview = 見工；interviewer = 面試官。"],
["responsible","/rɪˈspɒnsəbl/","adj.","負責的","要為某件事負責；有責任感。","Who is responsible for this project?","邊個負責呢個項目？","be responsible for + 事情。"],
["reliable","/rɪˈlaɪəbl/","adj.","可靠的","信得過、靠得住。","He is a reliable worker.","佢係一個可靠嘅員工。","動詞 rely on = 依靠。"],
["efficient","/ɪˈfɪʃnt/","adj.","有效率的","做嘢快又唔嘥時間、唔嘥資源。","This new system is more efficient.","呢個新系統更有效率。","efficient（有效率）同 effective（有效）意思唔同。"],
["environment","/ɪnˈvaɪrənmənt/","n.","環境","大自然環境，或者身邊嘅環境。","We should protect the environment.","我哋應該保護環境。","work environment = 工作環境。"],
["recycle","/ˌriːˈsaɪkl/","v.","回收","將用完嘅嘢回收再用。","We recycle bottles and paper.","我哋回收膠樽同紙。","recycling bin = 回收桶。"],
["reduce","/rɪˈdjuːs/","v.","減少","令數量或者程度變少。","We need to reduce plastic waste.","我哋要減少膠廢物。","reduce the cost（減低成本）/ reduce stress（減壓）。"],
["suggest","/səˈdʒest/","v.","建議","提出意見畀人參考。","I suggest we take a taxi.","我建議我哋搭的士。","suggest + doing 或者 suggest that...；唔講 suggest you to do。"],
["agree","/əˈgriː/","v.","同意","認同人哋嘅講法。","I agree with you.","我同意你。","唔好講 I am agree；agree with + 人。"],
["discuss","/dɪˈskʌs/","v.","討論","一齊傾、交換意見。","Let's discuss it at the meeting.","我哋喺會上討論下。","discuss 後面直接加名詞：discuss the plan（唔使加 about）。"],
["convenient","/kənˈviːniənt/","adj.","方便的","方便、唔麻煩。","Is Monday convenient for you?","星期一你方唔方便？","問人方唔方便：Is it convenient for you?（唔講 Are you convenient?）"],
["comfortable","/ˈkʌmftəbl/","adj.","舒服的","令人覺得舒適。","These shoes are very comfortable.","對鞋好舒服。","通常讀 COMF-ta-ble，三個音節。"],
["necessary","/ˈnesəsəri/","adj.","必要的","需要、一定要有。","Is it necessary to book first?","使唔使預先訂位？","串法：一個 c、兩個 s：ne-c-e-ss-ary。"],
["achieve","/əˈtʃiːv/","v.","達成；實現","努力之後做到目標。","You can achieve your dream.","你可以實現你嘅夢想。","achieve a goal；名詞 achievement = 成就。"],
["goal","/gəʊl/","n.","目標","想達到嘅目的；足球嘅「入波」都係 goal。","My goal is to speak English well.","我嘅目標係講好英文。","set a goal = 定目標；reach a goal = 達到目標。"],
["effort","/ˈefət/","n.","努力","付出嘅心機同力氣。","Thank you for your effort.","多謝你嘅努力。","make an effort = 盡力、畀心機。"],
["communicate","/kəˈmjuːnɪkeɪt/","v.","溝通","同人交流、傳達意思。","We communicate by email.","我哋用電郵溝通。","communicate with someone；名詞係 communication。"],
["explain","/ɪkˈspleɪn/","v.","解釋","講清楚點解或者點做。","Can you explain this word?","你可唔可以解釋下呢個字？","explain something to someone（唔講 explain me）。"],
["misunderstand","/ˌmɪsʌndəˈstænd/","v.","誤會","理解錯人哋嘅意思。","Please don't misunderstand me.","請你唔好誤會我。","名詞：misunderstanding：There was a misunderstanding.（有啲誤會）"],
["organise","/ˈɔːgənaɪz/","v.","組織；安排","搞活動、安排好或者執整齊。","Who will organise the party?","邊個負責搞個派對？","英式寫 organise，美式寫 organize。"],
["budget","/ˈbʌdʒɪt/","n.","預算","預先計好可以使幾多錢。","We are on a tight budget.","我哋嘅預算好緊。","on a budget = 慳住使；over budget = 超支。"],
["priority","/praɪˈɒrəti/","n.","優先事項","最重要、要最先處理嘅嘢。","Safety is our top priority.","安全係我哋嘅首要任務。","top priority = 最優先；動詞 prioritise = 排優先次序。"]
];
const WORDS = WORDS_RAW.map((r, i) => ({ id: i, day: Math.floor(i / 3) + 1, w: r[0], ipa: r[1], pos: r[2], zh: r[3], yue: r[4], ex: r[5], exZh: r[6], tip: r[7] }));
